graph TD;
    A["Développement de l'application"] --> B["Containerisation de l'application avec Docker"];
    B --> C["Orchestration de l'application avec Docker Compose"];
    C --> D["Téléchargement de l'application sur GitHub"];
    D --> E["Gestion des conteneurs Docker avec Harbor"];
    E --> F["Création du Pipeline avec Jenkins"];
    F --> G["Inspection continue avec SonarQube"];

